name: Build Telegram APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
      
    - name: Build Release APK
      run: |
        cd TMessagesProj
        ./gradlew assembleRelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Telegram-APK
        path: |
          TMessagesProj/build/outputs/apk/release/*.apk
          TMessagesProj/build/outputs/apk/*/*.apk
